### ISSUE TITLE
Eigen_Version

### ISSUE THREAD

**Issue by where2go947** [egdw/ORB_SLAM3_Ubuntu20.04#1]
Hi, thanks for your contribution to the installation of ORB_SLAM3 on ubuntu 20.04.

I have followed your instructions but met errors.
`DBoW2` and `g2o` were successfully built.
When configuring and building ORB_SLAM3 with `make -j`, there are many errors related to `Eigen3` like
```
/usr/local/include/eigen3/Eigen/src/Core/Transpose.h:35:45: error: no type named ‘StorageKind’ in ‘struct Eigen::internal::traits<const Eigen::SparseMatrix<double, 0> >’
   typedef typename nested<MatrixType>::type MatrixTypeNested;
```
And finally stopped as:
```
[ 68%] Building CXX object CMakeFiles/ORB_SLAM3.dir/src/TwoViewReconstruction.cc.o
......
......
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/build.make:232: CMakeFiles/ORB_SLAM3.dir/src/Optimizer.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:390: CMakeFiles/ORB_SLAM3.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
I guess it may be a eigen version problem?
I have installed eigen-3.3.7 with `sudo apt install libeigen3-dev` and verified it with `eigen3.pc`

In `CMakeLists.txt`, there is `find_package(Eigen3 3.1.0 REQUIRED)`
But it seems that eigen-3.3.7 have already been installed and linked to other packages.
What eigen version are you using? Does it really matters in building and linking?

Could you please give me some suggestions?
Thanks!

**Comment by egdw** [comment]
Hello, My friend.
I've been building this project for a while, and I've forgotten a lot of the details. However, based on the dependencies in cmakelist.txt, I chose eigen-3.1.0 as my dependency version, which is also the official version used by ORB_SLAM3 ([the official Cmakelist.txt link is here](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/CMakeLists.txt)). I haven't tested any other versions of eigen. You can try them out, but I suggest you stick with Eigen-3.1.0 for best compatibility.

**Comment by where2go947** [comment]
Thanks for your reply. 
I will try Eigen-3.1.0 out. 
Hope other packages would be fine : )
